from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from typing import List, Dict, Any
import os

class CitationGenerator:
    def __init__(self, output_path: str, project_id: int):
        self.output_path = output_path
        self.project_id = project_id
        self.doc = SimpleDocTemplate(output_path, pagesize=letter)
        self.styles = getSampleStyleSheet()
        
        # Custom styles
        self.title_style = ParagraphStyle(
            'CitationTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=colors.teal,
            spaceAfter=12
        )
        self.item_style = ParagraphStyle(
            'CitationItem',
            parent=self.styles['Normal'],
            fontSize=10,
            leading=14,
            spaceBefore=6
        )

    def generate(self, sources: List[Dict[str, Any]], company_name: str = "The Company"):
        """
        Generates a PDF citation document.
        sources: List of { "type": "url"|"file", "value": "...", "context": "..." }
        """
        elements = []
        
        # Title
        elements.append(Paragraph(f"Data Citation Report: {company_name}", self.title_style))
        elements.append(Paragraph(f"Project ID: {self.project_id}", self.styles['Normal']))
        elements.append(Spacer(1, 24))
        
        # Introduction
        intro_text = (
            "This document lists the sources and references used to generate the investment teaser. "
            "Kelp AI synthesizes data from both internal uploaded documents and public web sources."
        )
        elements.append(Paragraph(intro_text, self.styles['Normal']))
        elements.append(Spacer(1, 12))
        
        # Source Table
        data = [["Type", "Source", "Reference Context"]]
        for s in sources:
            stype = s.get("type", "General").capitalize()
            val = s.get("value", "N/A")
            ctx = s.get("context", "Used for narrative synthesis")
            
            # Trim long URLs
            if len(val) > 60:
                val = val[:57] + "..."
                
            data.append([stype, val, ctx])
            
        t = Table(data, colWidths=[60, 240, 180])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.teal),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('WORDWRAP', (0, 0), (-1, -1), True),
        ]))
        
        elements.append(t)
        
        # Footer
        elements.append(Spacer(1, 48))
        elements.append(Paragraph("Generated by Kelp AI. All rights reserved.", self.styles['Italic']))
        
        # Build PDF
        try:
            self.doc.build(elements)
            return True
        except Exception as e:
            print(f"PDF Citation Error: {e}")
            return False

def get_citation_generator(output_path: str, project_id: int) -> CitationGenerator:
    return CitationGenerator(output_path, project_id)
